# Generated by Django 3.1.9 on 2021-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
